CREATE DATABASE IF NOT EXISTS hemocare CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE hemocare;

CREATE TABLE IF NOT EXISTS users (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE,
 phone VARCHAR(30) NOT NULL, password_hash VARCHAR(100) NOT NULL, role ENUM('USER','ADMIN') NOT NULL DEFAULT 'USER',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS blood_inventory (
 blood_group VARCHAR(3) PRIMARY KEY, units INT NOT NULL DEFAULT 0,
 CONSTRAINT chk_inventory_units CHECK (units >= 0)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS donations (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, blood_group VARCHAR(3) NOT NULL, units INT NOT NULL,
 donation_date DATE NOT NULL, status ENUM('PENDING','APPROVED','REJECTED') NOT NULL DEFAULT 'PENDING',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT chk_donation_units CHECK (units > 0),
 CONSTRAINT fk_donation_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS blood_requests (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, blood_group VARCHAR(3) NOT NULL, units INT NOT NULL,
 patient_name VARCHAR(100) NOT NULL, hospital VARCHAR(160) NOT NULL, reason VARCHAR(500) NOT NULL,
 status ENUM('PENDING','APPROVED','REJECTED') NOT NULL DEFAULT 'PENDING', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT chk_request_units CHECK (units > 0),
 CONSTRAINT fk_request_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
INSERT INTO blood_inventory (blood_group,units) VALUES ('O+',12),('A+',10),('B+',8),('AB+',5),('O-',4),('A-',3),('B-',2),('AB-',1) ON DUPLICATE KEY UPDATE blood_group=VALUES(blood_group);
